name: Build Speedtest Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - '!**'
      - '.github/workflows/build.yaml'

env:
  DOCKERHUB_SLUG: "madnuttah/speedtest"
  VERSION: "0.3.1"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
           
      - name: Checkout source
        uses: actions/checkout@v4
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile   
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:${{ env.VERSION }}
            ${{ env.DOCKERHUB_SLUG }}:latest
          
